### ISSUE TITLE
The API is too hard to use.

### ISSUE THREAD

**Issue by yejiayu** [cryptape/bft-rs#68]
Why should I learn how to use the channel?

Recommend the API to be changed to the following.

```rust
pub trait BFT {
    fn set_proposal(p: Proposal) -> BFTResult<bool, Error>;
    fn set_vote(v: Vote) -> BFTResult<bool, Error>;

    fn start();
}

pub trait BFTProvider: Send + Sync {
    fn package_proposal(height: u64) -> BFTResult<Proposal, Error>;
    fn validate_proposal(p: Prposal) -> BFTResult<bool, Error>;
    fn commit(cm: CommitBlock) -> BFTResult<(), Error>;
    fn udpate_validate(height: u64) -> BFTResult<Vec<Validate>, Error>;
    // Broadcast blocks or votes can be split into two function.
    fn broadcast() -> BFTResult<(), Error>;
}

let provider = BFTProvider::new();

let bft = BFT::new(provider, signer);
bft.start();
```

ref [go-cita-tendermint](https://github.com/yejiayu/go-cita/blob/caec882aaa4bd2db46346a7000b1ecaab900a10a/consensus/tendermint/round_step.go#L37-L49)

**Comment by rev-chaos** [comment]
Great suggestion, we will assimilate this in v0.4 for better user experience.

**Comment by chaoticlonghair** [comment]
In fact, I have talked with @KaoImin yesterday.
I don't care about the APIs above (they are for the far future).

But, I think you should add some methods (simple and full compatible) to mask bft inner logic.
If you don't have time, I can do it.
