### ISSUE TITLE
vote type

### ISSUE THREAD

**Issue by yejiayu** [cryptape/bft-rs#69]
Here https://github.com/cryptape/bft-rs/blob/ce10282818743b28ec1837c72e404aecd6e10a14/src/lib.rs#L88-L99
why does the `vote_type` not use `prevote` and `precommit`.

@rev-chaos @KaoImin

**Comment by KaoImin** [comment]
@rev-chaos

**Comment by yejiayu** [comment]
why close? This issue has not been resolved.

**Comment by KaoImin** [comment]
The `vote_type` has changed into `enum VoteType`, and the issue has already resolved.

**Comment by yejiayu** [comment]
OK, but you'd better quote the corresponding issues in the relevant `PR`,  so that the people who care about know where they have been changed.

**Comment by KaoImin** [comment]
OK
